{
 "title": "Autopkgtest",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "SHOW TAG VALUES FROM autopkgtest_queue_size WITH KEY = \"instance\""
   }
  ]
 },
 "panels": [
  {
   "title": "autopkgtest queue size (by release)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_release",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"autopkgtest_queue_size\" WHERE (\"instance\" =~ /^$instance$/ OR (\"instance\" = \"production\" AND \"instance\" = 'null')) AND $timeFilter  GROUP BY time($__interval), \"release\" fill(null) ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "null" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest queue size (by arch)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "amd64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "amd64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "arm64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "arm64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "armhf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "armhf" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "i386",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "i386" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "ppc64el",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "ppc64el" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "riscv64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "riscv64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "s390x",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "s390x" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest job throughput (by arch)",
   "type": "graph",
   "description": "exited normally includes passes and fails, abnormally is for things like infrastructure problems. Abnormal also includes packages marked to never run.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_arch total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_exit_event",
     "query": "SELECT count(\"exited\") FROM \"autopkgtest_exit_event\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\" fill(null)",
     "select": [
      [
       { "params": [ "exited" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "exit_status", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "exit_status", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest jobs abnormal failure rate",
   "type": "graph",
   "description": "exited normally includes passes and fails, abnormally is for things like infrastructure problems. Abnormal also includes packages marked to never run.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_arch total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_exit_event",
     "query": "SELECT count(\"exited\") FROM \"autopkgtest_exit_event\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\" fill(null)",
     "select": [
      [
       { "params": [ "exited" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "exit_status", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "exit_status", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "$tag_arch (exited abnormally)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_exit_event",
     "query": "SELECT count(\"exited\") FROM \"autopkgtest_exit_event\" WHERE (\"exit_status\" = '16' OR \"exit_status\" = '20' OR \"exit_status\" = '99') AND (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\" fill(null)",
     "select": [
      [
       { "params": [ "exited" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "exit_status", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "exit_status", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest testbed failure count",
   "type": "graph",
   "description": "Tests that exit with code 16 or 20 are testbed or unexpected failures and are likely due to issues provisioning instances",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_arch (exited abnormally)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_exit_event",
     "query": "SELECT count(\"exited\") FROM \"autopkgtest_exit_event\" WHERE (\"exit_status\" = '16' OR \"exit_status\" = '20' OR \"exit_status\" = '99') AND (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\" fill(null)",
     "select": [
      [
       { "params": [ "exited" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "exit_status", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "exit_status", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest jobs finished per cloud",
   "type": "graph",
   "description": "exited normally includes passes and fails, abnormally is for things like infrastructure problems. Abnormal also includes packages marked to never run.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_arch/$tag_region (exited normally)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_exit_event",
     "query": "SELECT count(\"exited\") FROM \"autopkgtest_exit_event\" WHERE \"arch\" != 'armhf' AND (\"exit_status\" = '0' OR \"exit_status\" = '2' OR \"exit_status\" = '4' OR \"exit_status\" = '6' OR \"exit_status\" = '8' OR \"exit_status\" = '12') AND (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\",\"region\" fill(null)",
     "select": [
      [
       { "params": [ "exited" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "exit_status", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "exit_status", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "$tag_arch/$tag_region (exited abnormally)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_exit_event",
     "query": "SELECT count(\"exited\") FROM \"autopkgtest_exit_event\" WHERE \"arch\" != 'armhf' AND (\"exit_status\" = '16' OR \"exit_status\" = '20' OR \"exit_status\" = '99') AND (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\", \"region\" fill(null)",
     "select": [
      [
       { "params": [ "exited" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "exit_status", "operator": "=", "value": "0" },
      { "condition": "OR", "key": "exit_status", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Cloud workers in active / error",
   "type": "graph",
   "description": "A script is run hourly to reset all the error units to active, so you can expect this to be noisy.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_arch/$tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "autopkgtest_unit_status",
     "query": "SELECT sum(\"count\") FROM \"autopkgtest_unit_status\" WHERE (\"instance\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval), \"arch\", \"status\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "LXD remotes in active/error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_lxd_status",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "active" }
     ]
    },
    {
     "alias": "error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_lxd_status",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "error" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest queue size rate of change (for alerting)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "queue-amd64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "amd64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "amd64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "amd64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "queue-arm64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "arm64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "arm64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "arm64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "queue-armhf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "armhf" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "armhf",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "armhf" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "queue-i386",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "i386" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "i386",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "i386" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "queue-ppc64el",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "ppc64el" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "ppc64el",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "ppc64el" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "queue-riscv64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "riscv64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "riscv64",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "riscv64" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "queue-s390x",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "s390x" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    },
    {
     "alias": "s390x",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT difference(sum(\"count\")) FROM \"autopkgtest_queue_size\" WHERE (\"arch\" = 'amd64' AND \"instance\" = 'production') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "arch", "operator": "=", "value": "s390x" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "production" }
     ]
    }
   ]
  },
  {
   "title": "Instance Deletion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "too old",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_delete_event",
     "select": [
      [
       { "params": [ "deleted" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "deletion_reason", "operator": "=", "value": "instance_too_old" }
     ]
    },
    {
     "alias": "no autopkgtest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_delete_event",
     "select": [
      [
       { "params": [ "deleted" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "deletion_reason", "operator": "=", "value": "instance_no_autopkgtest" }
     ]
    },
    {
     "alias": "in error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_delete_event",
     "select": [
      [
       { "params": [ "deleted" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "deletion_reason", "operator": "=", "value": "instance_in_error" }
     ]
    }
   ]
  },
  {
   "title": "Apache 2 requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "403",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "apache2_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "403" }
     ]
    },
    {
     "alias": "200",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "apache2_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "200" }
     ]
    },
    {
     "alias": "429",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "apache2_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "429" }
     ]
    },
    {
     "alias": "404",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "apache2_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "404" }
     ]
    },
    {
     "alias": "500",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "apache2_requests",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "code", "operator": "=", "value": "500" }
     ]
    }
   ]
  },
  {
   "title": "Active Worker Units Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "amd64-unit-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "amd64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-2"
      }
     ]
    },
    {
     "alias": "arm64-unit-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "arm64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-2"
      }
     ]
    },
    {
     "alias": "ppc64el-unit-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "ppc64el" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-2"
      }
     ]
    },
    {
     "alias": "riscv64-unit-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "riscv64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-2"
      }
     ]
    },
    {
     "alias": "s390x-unit-0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "s390x" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-2"
      }
     ]
    },
    {
     "alias": "amd64-unit-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "amd64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-15"
      }
     ]
    },
    {
     "alias": "arm64-unit-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "arm64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-15"
      }
     ]
    },
    {
     "alias": "ppc64el-unit-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "ppc64el" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-15"
      }
     ]
    },
    {
     "alias": "riscv64-unit-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "riscv64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-15"
      }
     ]
    },
    {
     "alias": "s390x-unit-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "s390x" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-15"
      }
     ]
    },
    {
     "alias": "amd64-unit-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "amd64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-20"
      }
     ]
    },
    {
     "alias": "arm64-unit-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "arm64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-20"
      }
     ]
    },
    {
     "alias": "ppc64el-unit-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "ppc64el" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-20"
      }
     ]
    },
    {
     "alias": "riscv64-unit-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "riscv64" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-20"
      }
     ]
    },
    {
     "alias": "s390x-unit-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_unit_status_active_percentage",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "AND", "key": "arch", "operator": "=", "value": "s390x" },
      {
       "condition": "AND",
       "key": "hostname",
       "operator": "=",
       "value": "juju-7f2275-prod-proposed-migration-environment-20"
      }
     ]
    }
   ]
  }
 ]
}