{
 "title": "Ubuntu metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "release",
    "label": "Ubuntu Release",
    "query": "SHOW TAG VALUES FROM daily_image_details WITH KEY = \"release\""
   }
  ]
 },
 "panels": [
  {
   "title": "Ubuntu NEW or devel unapproved queue status (~ubuntu-archive / ~ubuntu-release)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_release $tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ubuntu_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "devel", "operator": "=", "value": "True" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "New" }
     ]
    }
   ]
  },
  {
   "title": "Uploads in queue longer than 10 days (~ubuntu-archive / ~ubuntu-release)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_release $tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "queue_ages",
     "select": [
      [
       { "params": [ "ten_day_backlog_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "devel", "operator": "=", "value": "True" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "New" }
     ]
    }
   ]
  },
  {
   "title": "SRU Unapproved queue size (~ubuntu-sru)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_release $tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "ubuntu_queue_size",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "devel", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "Unapproved" }
     ]
    }
   ]
  },
  {
   "title": "Uploads in queue longer than 10 days (~ubuntu-sru)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_release $tag_status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "queue_ages",
     "select": [
      [
       { "params": [ "ten_day_backlog_count" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "devel", "operator": "=", "value": "False" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "Unapproved" }
     ]
    }
   ]
  },
  {
   "title": "autopkgtest queue size (all releases)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_arch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "autopkgtest_queue_size",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"autopkgtest_queue_size\" WHERE (\"instance\" = 'production' OR \"instance\" = '') AND $timeFilter GROUP BY time(5m), \"arch\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=", "value": "production" },
      { "condition": "OR", "key": "instance", "operator": "=", "value": "null" }
     ]
    }
   ]
  },
  {
   "title": "rls-incoming / rls-tracking bugs ($release)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_team_name $tag_tag",
     "groupBy": [
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "team_name" ], "type": "tag" },
      { "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "distro_rls_bug_tasks",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=~", "value": "/^$release$/" }
     ]
    }
   ]
  },
  {
   "title": "Age of Latest Britney Run (Hours)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "alias": "$tag_release",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" }
     ],
     "measurement": "britney_last_run_age",
     "select": [
      [
       { "params": [ "run_age" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration of Latest Britney Run (Minutes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "$tag_release",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" }
     ],
     "measurement": "britney_last_run_duration",
     "select": [
      [
       { "params": [ "run_duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Command Not Found Age (Days)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "bionic",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "bionic" }
     ]
    },
    {
     "alias": "focal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "focal" }
     ]
    },
    {
     "alias": "jammy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "jammy" }
     ]
    },
    {
     "alias": "noble",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "noble" }
     ]
    },
    {
     "alias": "oracular",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "oracular" }
     ]
    },
    {
     "alias": "trusty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "trusty" }
     ]
    },
    {
     "alias": "xenial",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "xenial" }
     ]
    },
    {
     "alias": "resolute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "command_not_found_age",
     "select": [
      [
       { "params": [ "cnf_age" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=", "value": "resolute" }
     ]
    }
   ]
  },
  {
   "title": "Age of the Ubuntu Daily Images",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_flavor $tag_release $tag_current_or_pending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "flavor" ], "type": "tag" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "current_or_pending" ], "type": "tag" }
     ],
     "measurement": "daily_image_details",
     "select": [
      [
       { "params": [ "age" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "flavor", "operator": "=", "value": "ubuntu" },
      { "condition": "AND", "key": "release", "operator": "=~", "value": "/^$release$/" }
     ]
    }
   ]
  },
  {
   "title": "Update Excuses by Team count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_team",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "team" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "update_excuses_by_team_stats",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=~", "value": "/^$release$/" }
     ]
    }
   ]
  },
  {
   "title": "Sponsoring queue length",
   "type": "graph",
   "description": "Number of items in http://reqorts.qa.ubuntu.com/reports/sponsoring/index.html",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Items",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sponsoring_queue_stats",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "report", "operator": "=", "value": "sponsoring" }
     ]
    }
   ]
  },
  {
   "title": "Update Excuses by Team age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_team",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "team" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "update_excuses_by_team_stats",
     "select": [
      [
       { "params": [ "age" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=~", "value": "/^$release$/" }
     ]
    }
   ]
  },
  {
   "title": "Update Excuses stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "release" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "update_excuses_stats",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "valid_candidates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "valid_candidates" ], "type": "alias" }
      ],
      [
       { "params": [ "not_considered" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "not_considered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "release", "operator": "=~", "value": "/^$release$/" }
     ]
    }
   ]
  }
 ]
}